#!/bin/sh

[ -z "$1" ] && echo "Error: should be called from udhcpc" && exit 1

RESOLV_CONF="/etc/resolv.conf"
[ -n "$broadcast" ] && BROADCAST="broadcast $broadcast"
[ -n "$subnet" ] && NETMASK="netmask $subnet"

SERVICES_FILE="/etc/udhcpc_services"
UDHCPC_CONFDIR="/etc/udhcpc"
UDHCPC_CONF="$UDHCPC_CONFDIR/info.$interface"
UDHCPC_FALLBACK_IP="192.168.1.20"
UDHCPC_FALLBACK_NETMASK="255.255.255.0"

udhcpc_write_config()
{
	# store settings to UDHCPC_CONF
	mkdir -p $UDHCPC_CONFDIR
	cat > $UDHCPC_CONF << END
u_interface="$interface"
u_broadcast="$broadcast"
u_subnet="$subnet"
u_ip="$ip"
u_router="$router"
u_dns="$dns"
u_hostname="$hostname"
u_serverid="$serverid"
u_domain="$domain"
u_leasetime=$lease
u_timestamp="`date +%s`"
u_started=`sed 's/\([0-9]*\).*/\1/;' /proc/uptime`
u_pid=$PPID
END
}

udhcpc_compare_config()
{
	if [ ! -f $UDHCPC_CONF ]; then 
		return 1;
	fi

	. $UDHCPC_CONF

	if [ ".$u_interface" != ".$interface" ]; then return 1; fi
	if [ ".$u_broadcast" != ".$broadcast" ]; then return 1; fi
	if [ ".$u_subnet" != ".$subnet" ]; then return 1; fi
	if [ ".$u_ip" != ".$ip" ]; then return 1; fi
	if [ ".$u_router" != ".$router" ]; then return 1; fi
	if [ ".$u_domain" != ".$domain" ]; then return 1; fi
	if [ ".$u_dns" != ".$dns" ]; then return 1; fi

	return 0;
}

udhcpc_remove_config()
{
	rm -f $UDHCPC_CONF
}

restore_ip_aliases()
{
	ipaliases=`grep "ip addr add dev $interface" /etc/sysinit/net.conf`
        eval "$ipaliases"
}

configure_ipaddress()
{
	/sbin/ifconfig $interface $ip $BROADCAST $NETMASK
}

configure_routes()
{
	if [ -n "$router" ] ; then
		echo "deleting routers"
		while route del default gw 0.0.0.0 dev $interface 2> /dev/null ; do
			:
		done
		for i in $router ; do
			route add default gw $i dev $interface
			if [ ! $? -eq 0 ]; then
				route add -host $router dev $interface
				route add default gw $i dev $interface
			fi
		done
	fi
	/usr/etc/init.d/plugin start route
}
configure_dns()
{
	# do not remove resolv.conf if no dns servers received from dhcp
	if [ ".$dns" = "." ]; then
		return 0
	fi

	echo -n > $RESOLV_CONF
	[ -n "$domain" ] && echo search $domain >> $RESOLV_CONF
	for i in $dns ; do
		echo adding dns $i
		echo nameserver $i >> $RESOLV_CONF
	done
}

udhcpc_start_services()
{
	if [ ! -f $SERVICES_FILE ]; then 
		echo "File $SERVICES_FILE does not exist"
		return;
	fi

	for serv in `cat $SERVICES_FILE`; do
		/usr/etc/init.d/plugin start $serv
	done
}

udhcpc_stop_services()
{
	if [ ! -f $SERVICES_FILE ]; then 
		echo "File $SERVICES_FILE does not exist"
		return;
	fi

	rev_servlist=""
	for serv in `cat $SERVICES_FILE`; do
		rev_servlist="$serv $rev_servlist"
	done

	for serv in $rev_servlist; do
		/usr/etc/init.d/plugin stop $serv
	done
}

udhcpc_source_system_cfg()
{
	CFG_FILE="/tmp/running.cfg"
	if [ ! -f $CFG_FILE ]; then
		CFG_FILE="/tmp/system.cfg"
	fi
	eval `grep dhcpc\. $CFG_FILE | /bin/sed -e :1 -e 's/\(.*\)\.\(.*\)\(=\)/\1_\2\3/;t1' -e 's/\(.*=\)\(.*\)/\1\"\2\"/g'`
}

udhcpc_search_fallback()
{
	for i in 1 2 3 4; do
		devname=`eval echo '$'"dhcpc_${i}_devname"`
		fallback=`eval echo '$'"dhcpc_${i}_fallback"`
		fallback_netmask=`eval echo '$'"dhcpc_${i}_fallback_netmask"`
		if [ ! -z $devname ] && [ "x$devname" = "x$interface" ]; then
			[ ! -z $fallback ] && UDHCPC_FALLBACK_IP=$fallback
			[ ! -z $fallback_netmask ] && UDHCPC_FALLBACK_NETMASK=$fallback_netmask
			return
		fi
	done
}

udhcpc_internet_state() {
	if [ -x /bin/sysled ]; then
		/bin/sysled -i $1 2>/dev/null
	fi
	return 0
}

case "$1" in
	deconfig)
		if [ -e $UDHCPC_CONF ]; then
			udhcpc_stop_services
			# clear IP address from interface
			/sbin/ip addr flush dev $interface
		fi
		udhcpc_remove_config
		udhcpc_internet_state 0
		;;

	leasefail)
		udhcpc_remove_config
		udhcpc_source_system_cfg
		udhcpc_search_fallback
		/sbin/ifconfig $interface $UDHCPC_FALLBACK_IP netmask $UDHCPC_FALLBACK_NETMASK
                restore_ip_aliases
		udhcpc_internet_state 0
		;;

	bound)
		configure_ipaddress
		configure_routes
		configure_dns

		if [ -e $UDHCPC_CONF ]; then
			udhcpc_start_services
		fi
                
		udhcpc_write_config
                restore_ip_aliases
		udhcpc_internet_state 1
		;;

	renew)
		if ! udhcpc_compare_config; then
			udhcpc_stop_services

			configure_ipaddress
			configure_routes
			configure_dns

			udhcpc_start_services

			udhcpc_write_config
		fi
                restore_ip_aliases
		udhcpc_internet_state 1
		;;
esac

exit 0
